ShowcaseScreen:
    name: 'Pantalla Principal'
    
    fullscreen: True

    BoxLayout:
        size_hint_y: None
        height: '48dp'

        ToggleButton:
            id: tbh
            text: 'Ir Inicio'
            group: 'textinputs'
            
    Label:
        size_hint_y: None
        height: '48dp'
        text: 'BIENVENIDO INTRODUCION EAsta aplicacion te mostrara ehfff'
        
        
    

    
       

       
